image: Ubuntu1804 # образ для сборки
stack: node 10 # окружение
branches:
  only:
    - master # ветка git
cache: node_modules # кеширование
install:
  - yarn add # команда установки зависимостей
build: off
test_script:
  - yarn run lint && yarn test # скрипт сборки